swagger: "2.0"
info:
  description: "勤怠システム操作用API"
  version: "1.0.0"
  title: "Shusshar"
  # termsOfService: "http://swagger.io/terms/"
  # contact:
  #   email: "apiteam@swagger.io"
  # license:
  #   name: "Apache 2.0"
  #   url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/api/v1"
tags:
- name: "clarinet"
  description: "ネットde勤怠の操作"
# - name: "pet"
#   description: "Everything about your Pets"
#   externalDocs:
#     description: "Find out more"
#     url: "http://swagger.io"
# - name: "store"
#   description: "Access to Petstore orders"
# - name: "user"
#   description: "Operations about user"
#   externalDocs:
#     description: "Find out more about our store"
#     url: "http://swagger.io"
schemes:
- "http"
paths:
  /clarinet/status:
    post:
      tags:
      - "clarinet"
      summary: "自身の出退勤状態確認"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "ネットde勤怠のログインID/PWをパラメータとする"
        required: true
        schema:
          $ref: "#/definitions/Auth"
      responses:
        200:
          description: "OK"
          schema:
            type: object
            properties:
              status:
                type: string
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/ErrorResponse"

  /clarinet/punch:
    post:
      summary: "打刻する"
      description:
        "出退勤状態に応じて自動で出勤/退勤を行う<br/>2回続けて実行すると出勤後に即座に退勤処理が行われるため要注意"
      tags:
      - "clarinet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "ネットde勤怠のログインID/PWをパラメータとする"
        required: true
        schema:
          $ref: "#/definitions/Auth"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /clarinet/shussha:
    post:
      summary: "出社する"
      description: "出社できる場合に出社を行う<br/>2回続けて実行した場合エラーとなる"
      tags:
      - "clarinet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "ネットde勤怠のログインID/PWをパラメータとする"
        required: true
        schema:
          $ref: "#/definitions/Auth"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /clarinet/taisha:
    post:
      summary: "退社する"
      description: "退社できる場合に退社を行う<br/>2回続けて実行した場合エラーとなる"
      tags:
      - "clarinet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "ネットde勤怠のログインID/PWをパラメータとする"
        required: true
        schema:
          $ref: "#/definitions/Auth"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  Auth:
    type: object
    properties:
      login_id:
        description: "ネットde勤怠ID"
        type: string
      login_pass:
        description: "ネットde勤怠PW"
        type: string
  ErrorResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
# externalDocs:
#   description: "Find out more about Swagger"
#   url: "http://swagger.io"
